// automatically generated by the FlatBuffers compiler, do not modify

package fbs

const (
	EntityNONE = 0
	EntityPlayer = 1
	EntityBullet = 2
)

var EnumNamesEntity = map[int]string{
	EntityNONE:"NONE",
	EntityPlayer:"Player",
	EntityBullet:"Bullet",
}

