// automatically generated by the FlatBuffers compiler, do not modify

package fbs

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Heartbeat struct {
	_tab flatbuffers.Table
}

func GetRootAsHeartbeat(buf []byte, offset flatbuffers.UOffsetT) *Heartbeat {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Heartbeat{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *Heartbeat) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Heartbeat) Table() flatbuffers.Table {
	return rcv._tab
}

func HeartbeatStart(builder *flatbuffers.Builder) {
	builder.StartObject(0)
}
func HeartbeatEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
