// automatically generated by the FlatBuffers compiler, do not modify

package fbs

const (
	PacketNONE = 0
	PacketRespawn = 1
	PacketWorld = 2
	PacketPerception = 3
	PacketInputs = 4
)

var EnumNamesPacket = map[int]string{
	PacketNONE:"NONE",
	PacketRespawn:"Respawn",
	PacketWorld:"World",
	PacketPerception:"Perception",
	PacketInputs:"Inputs",
}

