// automatically generated by the FlatBuffers compiler, do not modify

package fbs

const (
	PacketNONE = 0
	PacketHeartbeat = 1
	PacketRespawn = 2
	PacketWorld = 3
	PacketPerception = 4
	PacketInputs = 5
	PacketDeath = 6
)

var EnumNamesPacket = map[int]string{
	PacketNONE:"NONE",
	PacketHeartbeat:"Heartbeat",
	PacketRespawn:"Respawn",
	PacketWorld:"World",
	PacketPerception:"Perception",
	PacketInputs:"Inputs",
	PacketDeath:"Death",
}

