// automatically generated by the FlatBuffers compiler, do not modify

package fbs

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Perception struct {
	_tab flatbuffers.Table
}

func GetRootAsPerception(buf []byte, offset flatbuffers.UOffsetT) *Perception {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Perception{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *Perception) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Perception) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Perception) Health() uint16 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint16(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Perception) MutateHealth(n uint16) bool {
	return rcv._tab.MutateUint16Slot(4, n)
}

func (rcv *Perception) Snapshots(obj *Snapshot, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *Perception) SnapshotsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func PerceptionStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func PerceptionAddHealth(builder *flatbuffers.Builder, health uint16) {
	builder.PrependUint16Slot(0, health, 0)
}
func PerceptionAddSnapshots(builder *flatbuffers.Builder, snapshots flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(snapshots), 0)
}
func PerceptionStartSnapshotsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func PerceptionEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
