// automatically generated by the FlatBuffers compiler, do not modify

package fbs

const (
	TeamNone = 0
	TeamHunters = 1
	TeamGhosts = 2
)

var EnumNamesTeam = map[int]string{
	TeamNone:"None",
	TeamHunters:"Hunters",
	TeamGhosts:"Ghosts",
}

